### ISSUE TITLE
Global instances of formatters

### ISSUE THREAD

**Issue by Regan-Koopmans** [pytroll/trollsift#37]
[This](https://github.com/pytroll/trollsift/blob/main/trollsift/parser.py#L372) global instance of `RegexFormatter` is not thread-safe. If multiple concurrent calls are made to [parse](https://github.com/pytroll/trollsift/blob/main/trollsift/parser.py#L446) the `_cached_fields` dictionary will be shared between them, and we cannot guarantee that calls will not interfere with one another. I believe that a `RegexFormatter` could be created per function call. This would have some marginal computational overhead, but ensure thread-safety. 

I was lead to this issue because of some cryptic infrequent exceptions that occur when calling `parse` using many threads. I am happy to provide a fix for this, but I wanted to hear from the maintainers whether there was a reason for keeping these formatters global.

**Comment by djhoese** [comment]
So I'm a little torn on the best solution for this. On one hand the whole point of switching to regular expressions for parsing was to make a repeatable "compiled" parser that could be cached and therefore faster. On the other hand, we don't want to disallow threading or multi-process workflows.

Looking at the code I wrote (a while ago), I'm not sure there is much of a purpose to the global RegexFormatter object, right? Or at least the responsibilities could be moved around. The main point of the global instance I think was so the `lru_cache`'d `format` method could persist across multiple `format` and `extract_values` calls. When you are repeatedly converting/parsing the same format strings over and over again this should be a huge time savings. But in the cases where all format strings are unique, you don't benefit from this at all.

Next topic: The `_cached_fields` is only used during the `format` call and all sub-method calls triggered from it. After that the dictionary is cleared. From what I can tell this instance property only exists as an instance property because we are using the Python Formatter interface and can't add new kwargs wherever we want. When initially looking at the code again I thought maybe we could replace the `_cached_fields` with a new dictionary `{}` and that would fix the problem, but since it still assigns to `_cached_fields` it would still be used by both threads. Plus this feature only helps when the same field appears twice in the same format string (and to validate that it doesn't change).

Next, we can't make a ton of instances of RegexFormatter because of the way we are using `lru_cache` on format. It will cause a memory leak where the formatter instances don't get garbage collected:

https://youtu.be/sVjtp6tGo0g

I only learned about this after adding this code, but looking at it now we need to be careful.

So what are our options:

1. Remove the lru_cache and make a new formatter object every time we need it.
2. Same as 1, but also add lru_cache to the functions that use it. See below.
3. Add a `lock` to the `format` method so it can only be run one thread at a time. Unfortunate for something as simple as a `_cached_field` dictionary.
4. Somehow make a thread specific cached_field dictionary...seems annoyingly complex.
5. Something else?

## Option 2

I think option 2 above is the best option, but requires some restructuring. If we make a function called something like `regex_format` that has `lru_cache` on it then it could create the RegexFormatter, then call `.format` on it, and return the result. This means no memory leak on the formatter class, only a single cached field dictionary per call, and we still get caching.

This does mean that `RegexFormatter.extract_values` has to be moved to an external function (global level) that calls the above mentioned cached `regex_format` function. This shouldn't be too bad.

@Regan-Koopmans What do you think of this?

**Comment by Regan-Koopmans** [comment]
@djhoese Option 2 seems like a good solution to me. I will probably have capacity to create a pull-request for this during the weekend, or would you prefer to work on this change personally?

**Comment by djhoese** [comment]
If you're up for it then give it a go. Once you have a good start on it you can make the pull request and we can discuss how it "feels" and come up with any new ideas then. Thanks for bringing this up.
